version: "2"
run:
  tests: true

linters:
  enable:
    - misspell
    - unconvert
    - unparam
  settings:
    errcheck:
      check-blank: false
  exclusions:
    generated: lax
    paths:
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/skaldlabs/skald-go
